### PR TITLE
Assign languages to all code blocks

### PR DESCRIPTION
**Pull request by 000wan**
Good to see such a cool project.
I've specified languages to all code blocks in tutorials and readme, which enables syntax highlighting.

### CODE REVIEW

**Review by leolara — APPROVED** [review]

**Comment by qwang98** [comment]
@000wan You can feel free to merge once the work flow run clears. Thanks for fixing.

**Comment by 000wan** [comment]
Thx! It seems I don't have a write access to merge PR so looking for maintainers @leolara @qwang98.

**Comment by leolara** [comment]
@000wan you need to fix the build there is an error, click on details to see the error

**Comment by leolara** [comment]
The build problem was fixed in main, and then I merged it

**Pull request merged**
