### PR TITLE
Move use chiquito::dsl::cb::* to circuit lambda

### PR DESCRIPTION
**Pull request by jae-cuz**
Hi maintainers, I'm student from PSE Summer Contribution program.

I just followed the mentioned part in #22 .

Comments would help me a lot :) Thanks!

### CODE REVIEW

**Comment by jae-cuz** [comment]
And I suppose you meant result_plaf in println?
https://github.com/privacy-scaling-explorations/chiquito/blob/c4891ae4e670704a9fe8d0875a390689d25877d5/examples/fibonacci.rs#L152-L154

Please let me know if you want separate issue for this or not. Thanks :)

**Comment by qwang98** [comment]
> And I suppose you meant result_plaf in println?
> 
> https://github.com/privacy-scaling-explorations/chiquito/blob/c4891ae4e670704a9fe8d0875a390689d25877d5/examples/fibonacci.rs#L152-L154
> 
> Please let me know if you want separate issue for this or not. Thanks :)

Yes. Thanks for catching. Please fix. Thanks!

**Review by qwang98 — APPROVED** [review]
Feel free to merge after fixing the result_plaf.

**Comment by qwang98** [comment]
@jae-cuz Feel free to merge once the work flow run clears!

**Comment by jae-cuz** [comment]
@qwang98 Should I fmt or leave it?

Also, could you explain what we can do for all the release fails (including other prs) ? Thanks.

**Comment by leolara** [comment]
@jae-cuz you should fix the build before merging. You can click on details on the failed checks see what are the errors and fix them.

One thing that can help is to run `make precommit`

**Comment by leolara** [comment]
There was previously one build error that was not related to this and fixed in main. However, the Rustfmt error stays, and should be fixed in this PR before merging

**Comment by jae-cuz** [comment]
@leolara Thanks for your kind explanation!

**Comment by qwang98** [comment]
@leolara Is there also a way to allow non-maintainers to run CI jobs in the settings?

**Comment by qwang98** [comment]
I merged this for now but I think we should enable non maintainers to merge in the future.

**Pull request merged**
