### PR TITLE
Github workflow to publish pypi python package

### LINKED ISSUE #91: Give instructions or add to CI for updating pip package

### PR DESCRIPTION
**Pull request by trangnv**
Resolve #91 
- We need to have PYPI_API_TOKEN as repo secret
- workflow will run with tag "v*" e.g. `git tag v1.0.0`

### CODE REVIEW

**Comment by leolara** [comment]
@trangnv there is a CI task failing, is it because PYPI_API_TOKEN is not set?

**Comment by leolara** [comment]
> workflow will run with tag "v*" e.g. git tag v1.0.0

does this mean that the package is only published when a tag is added?

**Comment by trangnv** [comment]
> @trangnv there is a CI task failing, is it because PYPI_API_TOKEN is not set?

That's right, I dont have the right to set the repo secret.


> > workflow will run with tag "v*" e.g. git tag v1.0.0
> 
> does this mean that the package is only published when a tag is added?

Yes, we might not want to build and publish python package everytime we merge. But let me check again with the forked one if that works as intended.

**Comment by leolara** [comment]
> > @trangnv there is a CI task failing, is it because PYPI_API_TOKEN is not set?
> 
> 
> 
> That's right, I dont have the right to set the repo secret.
> 
> 
> 
> 
> 
> > > workflow will run with tag "v*" e.g. git tag v1.0.0
> 
> > 
> 
> > does this mean that the package is only published when a tag is added?
> 
> 
> 
> Yes, we might not want to build and publish python package everytime we merge. But let me check again with the forked one if that works as intended.

Thanks I think for now we would like to use as versions the following format: vYYYY_MM_DD

**Comment by leolara** [comment]
Actually we decided on v0.1.YYYYMMDDrr where rr is 00 or 01 if we need to release more than once a day

**Review by leolara — APPROVED** [review]

**Comment by leolara** [comment]
@trangnv you can merge now, thanks

**Comment by leolara** [comment]
I am going to merge this because another PR needs this to be merged before continuing

**Pull request merged**
