### PR TITLE
WIP: Issue 75 add unit tests to DSL

### PR DESCRIPTION
**Pull request by nullbitx8**
This is a work in progress for https://github.com/privacy-scaling-explorations/chiquito/issues/75

I am planning to add code coverage as well as more tests.

### CODE REVIEW

**Comment by leolara** [comment]
Good, but missing more things to test

**Comment by leolara** [comment]
@nullbitx8 fix the fmt please

**Comment by nullbitx8** [comment]
> @nullbitx8 fix the fmt please

Will do. I plan on adding more tests, would you prefer I keep working on this PR or on another?

**Comment by leolara** [comment]
It is good to keep working on this. Thanks

**Review by leolara — APPROVED** [review]

**Pull request merged**
