### PR TITLE
implemented get_type function

### PR DESCRIPTION
**Pull request by rutefig**
deref type and if it's None return "field"

### CODE REVIEW

**Comment by leolara** [comment]
Closes #227

**Review by leolara — APPROVED** [review]

**Comment by leolara** [comment]
@rutefig Beautiful ❤️ 

Why do you need unwrap?

**Comment by leolara** [comment]
like, you could return `_ty` ? I think

**Comment by leolara** [comment]
I mean ty.as_deref ?

**Comment by rutefig** [comment]
> like, you could return `_ty` ? I think

yes you're right thank you 🙏🏼

**Pull request merged**
