### PR TITLE
add unit test code for FixedGenContext - Issue #104

### PR DESCRIPTION
**Pull request by saeyoon17**
Hi, I wrote two unit tests regarding FixedGenContext as suggested in Issue #104.

- test_fixed_gen_context() checks the length of assignment is 1 given a single fixed column.
- test_fixed_gen_context_multiple() checks the length of assignment is 2 given two column assignments.

Please let me know if anything else is required. :)

### CODE REVIEW

**Comment by leolara** [comment]
@saeyoon17 I think we should test that the values are correct, not just the length

**Comment by saeyoon17** [comment]
@leolara I changed the test so that it now checks the value. Please tell me if there are any other modifications we should make. :)

**Review by leolara — APPROVED** [review]

**Comment by leolara** [comment]
@saeyoon17 it is approved, does it show the button to merge to you?

**Comment by saeyoon17** [comment]
@leolara No.. I think I only have the read access to this repository. This is how I see it:

image

**Comment by qwang98** [comment]
@leolara  I think only maintainers are allowed to merge it. Any means we can change this in the repo settings?

**Pull request merged**
